version: '3.5'
services:

  dbpostgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: yaga-talk

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
      - './keycloak/scripts/create-users.sh:/opt/keycloak/bin/create-users.sh'
    command:
      - 'start-dev --import-realm --health-enabled=true'
