### Login in keycloak
POST http://localhost:9090/realms/yagatalk/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=yagatalk-public-client&grant_type=password&username=author1&password=author1

> {%
    client.test("login is successful", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("access_token", response.body["access_token"])
    });
%}

###
GET http://localhost:8082/api/assistants
Authorization: Bearer {{access_token}}

###