POST http://localhost:8082/api/chat/sessions
Content-Type: application/json

{
     "contextId":"a1e7e851-505b-4b62-b4de-5a56d46ee843"
}
###
POST http://localhost:8082/api/chat/sessions/38ec9db4-a797-4f9b-b756-17afa59605e7/messages
Content-Type: application/json

{
  "text":"Привет, ну че как там с деньгами?!"
}

###

GET http://localhost:8082/api/chat/sessions/38ec9db4-a797-4f9b-b756-17afa59605e7/messages

###

GET http://localhost:8082/api/chat/sessions/38ec9db4-a797-4f9b-b756-17afa59605e7/messages?createdAfterMs=1688588282624
